name: build

on:
  push:
    branches:
      - main
      - features/**
      - fixes/**
  pull_request:
  workflow_dispatch:
    inputs:
      gitops-version:
        description: 'GitOps version to use'
        required: true
        default: 'main'
        type: string

jobs:
  build:
    name: Build
    uses: ae-utbm/gitops/.github/workflows/pnpm-image-build-publish.yml@features/initial-setup
    with:
      # Replace theses values to the ones according your project
      pnpm-lint-script: 'lint'
      node-version: '18'